### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by colinmollenhour** [jreinke/magento-admin-launcher#2]
When I enabled products and categories something broke and now when I search I get these errors logged (Chrome):

![ss](http://content.screencast.com/users/colinmollenhour/folders/Jing/media/f5cbe3b7-4335-4121-a961-5df57afd37df/2013-03-26_1504.png)

**Comment by colinmollenhour** [comment]
Actually the error only seems to occur when searching categories..

**Comment by jreinke** [comment]
I can't reproduce this. It seems that a category does not have name, this is weird.
Can you provide result of `/admin/bubble_launcher/index` request please ?
